// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProducto = `-- name: CreateProducto :one
INSERT INTO producto (
    nombre, categoria, precio
) VALUES (
    $1, $2, $3
)
RETURNING id, nombre, categoria, precio
`

type CreateProductoParams struct {
	Nombre    string
	Categoria string
	Precio    pgtype.Numeric
}

func (q *Queries) CreateProducto(ctx context.Context, arg CreateProductoParams) (Producto, error) {
	row := q.db.QueryRow(ctx, createProducto, arg.Nombre, arg.Categoria, arg.Precio)
	var i Producto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Categoria,
		&i.Precio,
	)
	return i, err
}

const deleteProducto = `-- name: DeleteProducto :exec
DELETE FROM producto
WHERE id = $1
`

func (q *Queries) DeleteProducto(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProducto, id)
	return err
}

const getProducto = `-- name: GetProducto :one
SELECT id, nombre, categoria, precio FROM producto
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProducto(ctx context.Context, id int64) (Producto, error) {
	row := q.db.QueryRow(ctx, getProducto, id)
	var i Producto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Categoria,
		&i.Precio,
	)
	return i, err
}

const listProductos = `-- name: ListProductos :many
SELECT id, nombre, categoria, precio FROM producto
ORDER BY nombre
`

func (q *Queries) ListProductos(ctx context.Context) ([]Producto, error) {
	rows, err := q.db.Query(ctx, listProductos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Producto
	for rows.Next() {
		var i Producto
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Categoria,
			&i.Precio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProducto = `-- name: UpdateProducto :one
UPDATE producto
SET 
    nombre = $1,
    categoria = $2,
    precio = $3
WHERE id = $4
RETURNING id, nombre, categoria, precio
`

type UpdateProductoParams struct {
	Nombre    string
	Categoria string
	Precio    pgtype.Numeric
	ID        int64
}

func (q *Queries) UpdateProducto(ctx context.Context, arg UpdateProductoParams) (Producto, error) {
	row := q.db.QueryRow(ctx, updateProducto,
		arg.Nombre,
		arg.Categoria,
		arg.Precio,
		arg.ID,
	)
	var i Producto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Categoria,
		&i.Precio,
	)
	return i, err
}
